In [1]:
import pandas as pd
import numpy as np
books=pd.read_csv('Books.csv')
users=pd.read_csv('Users.csv')
ratings=pd.read_csv('Ratings.csv')

/var/folders/ng/5883tls546s98nnlzzj3v7yh0000gr/T/ipykernel_5755/3160263020.py:3: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  books=pd.read_csv('Books.csv')

In [2]:
print(books.shape)
print(users.shape)
print(ratings.shape)

(271360, 8)
(278858, 3)
(1149780, 3)

In [3]:

print(books['Image-URL-S'][0])

http://images.amazon.com/images/P/0195153448.01.THUMBZZZ.jpg

In [4]:
books.isnull().sum()
users.isnull().sum()
ratings.isnull().sum()

User-ID        0
ISBN           0
Book-Rating    0
dtype: int64

In [5]:
users.duplicated().sum()

0

POPULARITY BASED

In [6]:
ratings_with_name=ratings.merge(books, on ='ISBN')

In [7]:
ratings_with_name

,User-ID,ISBN,Book-Rating,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,276725,034545104X,0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
1,276726,0155061224,5,Rites of Passage,Judith Rae,2001,Heinle,http://images.amazon.com/images/P/0155061224.0...,http://images.amazon.com/images/P/0155061224.0...,http://images.amazon.com/images/P/0155061224.0...
2,276727,0446520802,0,The Notebook,Nicholas Sparks,1996,Warner Books,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...
3,276729,052165615X,3,Help!: Level 1,Philip Prowse,1999,Cambridge University Press,http://images.amazon.com/images/P/052165615X.0...,http://images.amazon.com/images/P/052165615X.0...,http://images.amazon.com/images/P/052165615X.0...
4,276729,0521795028,6,The Amsterdam Connection : Level 4 (Cambridge ...,Sue Leather,2001,Cambridge University Press,http://images.amazon.com/images/P/0521795028.0...,http://images.amazon.com/images/P/0521795028.0...,http://images.amazon.com/images/P/0521795028.0...
...,...,...,...,...,...,...,...,...,...,...
1031131,276704,0876044011,0,Edgar Cayce on the Akashic Records: The Book o...,Kevin J. Todeschi,1998,A.R.E. Press (Association of Research &amp; Enlig,http://images.amazon.com/images/P/0876044011.0...,http://images.amazon.com/images/P/0876044011.0...,http://images.amazon.com/images/P/0876044011.0...
1031132,276704,1563526298,9,Get Clark Smart : The Ultimate Guide for the S...,Clark Howard,2000,Longstreet Press,http://images.amazon.com/images/P/1563526298.0...,http://images.amazon.com/images/P/1563526298.0...,http://images.amazon.com/images/P/1563526298.0...
1031133,276706,0679447156,0,Eight Weeks to Optimum Health: A Proven Progra...,Andrew Weil,1997,Alfred A. Knopf,http://images.amazon.com/images/P/0679447156.0...,http://images.amazon.com/images/P/0679447156.0...,http://images.amazon.com/images/P/0679447156.0...
1031134,276709,0515107662,10,The Sherbrooke Bride (Bride Trilogy (Paperback)),Catherine Coulter,1996,Jove Books,http://images.amazon.com/images/P/0515107662.0...,http://images.amazon.com/images/P/0515107662.0...,http://images.amazon.com/images/P/0515107662.0...
1031135,276721,0590442449,10,Fourth Grade Rats,Jerry Spinelli,1996,Scholastic,http://images.amazon.com/images/P/0590442449.0...,http://images.amazon.com/images/P/0590442449.0...,http://images.amazon.com/images/P/0590442449.0...

In [8]:
num_rating_df=ratings_with_name.groupby('Book-Title').count()['Book-Rating'].reset_index()
num_rating_df.rename(columns={'Book-Rating':'num-ratings'},inplace=True)
num_rating_df

                                               Book-Title  num-ratings
0        A Light in the Storm: The Civil War Diary of ...            4
1                                   Always Have Popsicles            1
2                    Apple Magic (The Collector's series)            1
3        Ask Lily (Young Women of Faith: Lily Series, ...            1
4        Beyond IBM: Leadership Marketing and Finance ...            1
...                                                   ...          ...
241066                                      Ãƒ?Ã‚?lpiraten.            2
241067                     Ãƒ?Ã‚?rger mit Produkt X. Roman.            4
241068                                Ãƒ?Ã‚?sterlich leben.            1
241069                              Ãƒ?Ã‚?stlich der Berge.            3
241070                                  Ãƒ?Ã‚?thique en toc            2

[241071 rows x 2 columns]

In [9]:
print(ratings_with_name['Book-Rating'].dtype)
print(ratings_with_name['Book-Rating'].isnull().sum())

int64
0

In [10]:
ratings_with_name['Book-Rating'] = ratings_with_name['Book-Rating'].fillna(0)

# Calculate mean ratings by grouping 'Book-Title'
avg_rating_df = ratings_with_name.groupby('Book-Title')['Book-Rating'].mean().reset_index()

# Rename the 'Book-Rating' column to 'avg-ratings'
avg_rating_df.rename(columns={'Book-Rating': 'avg-ratings'}, inplace=True)

# Print the resulting DataFrame
print(avg_rating_df)

                                               Book-Title  avg-ratings
0        A Light in the Storm: The Civil War Diary of ...     2.250000
1                                   Always Have Popsicles     0.000000
2                    Apple Magic (The Collector's series)     0.000000
3        Ask Lily (Young Women of Faith: Lily Series, ...     8.000000
4        Beyond IBM: Leadership Marketing and Finance ...     0.000000
...                                                   ...          ...
241066                                      Ãƒ?Ã‚?lpiraten.     0.000000
241067                     Ãƒ?Ã‚?rger mit Produkt X. Roman.     5.250000
241068                                Ãƒ?Ã‚?sterlich leben.     7.000000
241069                              Ãƒ?Ã‚?stlich der Berge.     2.666667
241070                                  Ãƒ?Ã‚?thique en toc     4.000000

[241071 rows x 2 columns]

In [11]:
popular_df=num_rating_df.merge(avg_rating_df,on ='Book-Title')
popular_df

,Book-Title,num-ratings,avg-ratings
0,A Light in the Storm: The Civil War Diary of ...,4,2.250000
1,Always Have Popsicles,1,0.000000
2,Apple Magic (The Collector's series),1,0.000000
3,"Ask Lily (Young Women of Faith: Lily Series, ...",1,8.000000
4,Beyond IBM: Leadership Marketing and Finance ...,1,0.000000
...,...,...,...
241066,Ãƒ?Ã‚?lpiraten.,2,0.000000
241067,Ãƒ?Ã‚?rger mit Produkt X. Roman.,4,5.250000
241068,Ãƒ?Ã‚?sterlich leben.,1,7.000000
241069,Ãƒ?Ã‚?stlich der Berge.,3,2.666667
241070,Ãƒ?Ã‚?thique en toc,2,4.000000

In [12]:
popular_df=popular_df[popular_df['num-ratings']>=250].sort_values('avg-ratings',ascending=False).head(50)

In [13]:
popular_df = popular_df.merge(books,on='Book-Title').drop_duplicates('Book-Title')[['Book-Title','Book-Author','Image-URL-M','num-ratings','avg-ratings']]

COLLABORATIVE

In [14]:
x=ratings_with_name.groupby('User-ID').count()['Book-Rating']>200
padhe_likhe= x[x].index

In [15]:
filtered_rating=ratings_with_name[ratings_with_name['User-ID'].isin(padhe_likhe)]

In [16]:
filtered_rating

,User-ID,ISBN,Book-Rating,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
1150,277427,002542730X,10,Politically Correct Bedtime Stories: Modern Ta...,James Finn Garner,1994,John Wiley &amp; Sons Inc,http://images.amazon.com/images/P/002542730X.0...,http://images.amazon.com/images/P/002542730X.0...,http://images.amazon.com/images/P/002542730X.0...
1151,277427,0026217457,0,Vegetarian Times Complete Cookbook,Lucy Moll,1995,John Wiley &amp; Sons,http://images.amazon.com/images/P/0026217457.0...,http://images.amazon.com/images/P/0026217457.0...,http://images.amazon.com/images/P/0026217457.0...
1152,277427,003008685X,8,Pioneers,James Fenimore Cooper,1974,Thomson Learning,http://images.amazon.com/images/P/003008685X.0...,http://images.amazon.com/images/P/003008685X.0...,http://images.amazon.com/images/P/003008685X.0...
1153,277427,0030615321,0,"Ask for May, Settle for June (A Doonesbury book)",G. B. Trudeau,1982,Henry Holt &amp; Co,http://images.amazon.com/images/P/0030615321.0...,http://images.amazon.com/images/P/0030615321.0...,http://images.amazon.com/images/P/0030615321.0...
1154,277427,0060002050,0,On a Wicked Dawn (Cynster Novels),Stephanie Laurens,2002,Avon Books,http://images.amazon.com/images/P/0060002050.0...,http://images.amazon.com/images/P/0060002050.0...,http://images.amazon.com/images/P/0060002050.0...
...,...,...,...,...,...,...,...,...,...,...
1029357,275970,1931868123,0,There's a Porcupine in My Outhouse: Misadventu...,Mike Tougias,2002,Capital Books (VA),http://images.amazon.com/images/P/1931868123.0...,http://images.amazon.com/images/P/1931868123.0...,http://images.amazon.com/images/P/1931868123.0...
1029358,275970,3411086211,10,Die Biene.,Sybil GrÃƒ?Ã‚Â¤fin SchÃƒ?Ã‚Â¶nfeldt,1993,"Bibliographisches Institut, Mannheim",http://images.amazon.com/images/P/3411086211.0...,http://images.amazon.com/images/P/3411086211.0...,http://images.amazon.com/images/P/3411086211.0...
1029359,275970,3829021860,0,The Penis Book,Joseph Cohen,1999,Konemann,http://images.amazon.com/images/P/3829021860.0...,http://images.amazon.com/images/P/3829021860.0...,http://images.amazon.com/images/P/3829021860.0...
1029360,275970,4770019572,0,Musashi,Eiji Yoshikawa,1995,Kodansha International (JPN),http://images.amazon.com/images/P/4770019572.0...,http://images.amazon.com/images/P/4770019572.0...,http://images.amazon.com/images/P/4770019572.0...
1029361,275970,9626340762,8,Northanger Abbey (Classic Literature with Clas...,Jane Austen,1996,Naxos Audiobooks Ltd.,http://images.amazon.com/images/P/9626340762.0...,http://images.amazon.com/images/P/9626340762.0...,http://images.amazon.com/images/P/9626340762.0...

In [17]:
y=filtered_rating.groupby('Book-Title').count()['Book-Rating']>=50
famous_books=y[y].index

In [18]:
final_rating=filtered_rating[ratings_with_name['Book-Title'].isin(famous_books)]

/var/folders/ng/5883tls546s98nnlzzj3v7yh0000gr/T/ipykernel_5755/3486608508.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  final_rating=filtered_rating[ratings_with_name['Book-Title'].isin(famous_books)]

In [19]:
pt=final_rating.pivot_table(index='Book-Title',columns='User-ID',values='Book-Rating')

In [20]:
pt.fillna(0,inplace=True)

In [21]:
pt

User-ID,254,2276,2766,2977,3363,4017,4385,6251,6323,6543,...,271705,273979,274004,274061,274301,274308,275970,277427,277639,278418
Book-Title,,,,,,,,,,,,,,,,,,,,,
1984,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1st to Die: A Novel,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2nd Chance,0.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4 Blondes,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
A Bend in the Road,0.0,0.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Year of Wonders,0.0,0.0,0.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
You Belong To Me,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Zen and the Art of Motorcycle Maintenance: An Inquiry into Values,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Zoya,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"\O\"" Is for Outlaw""",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,8.0,0.0,0.0,0.0,0.0,0.0

In [22]:
from sklearn.metrics.pairwise import cosine_similarity

In [26]:
similarity_score=cosine_similarity(pt)

In [30]:
def recommend(book_name):
    index = np.where(pt.index == book_name)[0][0]
    similar_items = sorted(list(enumerate(similarity_score[index])), key=lambda x:x[1], reverse=True)[1:8]
    data=[]
    for i in similar_items:
        item=[]
        temp_df=books[books['Book-Title']==pt.index[i[0]]]
        item.extend(list(temp_df.drop_duplicates('Book-Title')['Book-Title']))
        item.extend(list(temp_df.drop_duplicates('Book-Title')['Book-Author']))
        item.extend(list(temp_df.drop_duplicates('Book-Title')['Image-URL-M']))

        data.append(item)
    return data

In [31]:
similarity_score[1]

array([0.10255025, 1.        , 0.2364573 , 0.        , 0.1095379 ,
       0.10092909, 0.11786249, 0.18761978, 0.09658879, 0.04716095,
       0.09790994, 0.07830823, 0.19121955, 0.04828673, 0.11297907,
       0.11424415, 0.11290848, 0.08432401, 0.05619509, 0.09820417,
       0.17562977, 0.05779941, 0.15727218, 0.05719732, 0.11374482,
       0.        , 0.09515326, 0.08104912, 0.02894774, 0.07225874,
       0.01714222, 0.03288122, 0.04211669, 0.09380106, 0.04486288,
       0.25375719, 0.04682287, 0.20897363, 0.05826367, 0.30746648,
       0.05386542, 0.06892792, 0.04503831, 0.074284  , 0.13507508,
       0.05023148, 0.02267079, 0.06552582, 0.05644729, 0.06294081,
       0.07553841, 0.05578722, 0.        , 0.19483247, 0.07717041,
       0.01504361, 0.10744436, 0.05396449, 0.08539351, 0.10668897,
       0.11024468, 0.        , 0.02769053, 0.23980848, 0.08922627,
       0.04639526, 0.04350087, 0.09616002, 0.1153737 , 0.01531666,
       0.13588642, 0.03504529, 0.12520455, 0.12647968, 0.10989717,
       0.1251211 , 0.08424927, 0.08526122, 0.05026875, 0.15698134,
       0.09433674, 0.07912157, 0.07627439, 0.        , 0.01589551,
       0.06294455, 0.06431867, 0.15156308, 0.05013144, 0.10249303,
       0.10971866, 0.        , 0.10874068, 0.03050783, 0.05725778,
       0.07877703, 0.19638405, 0.14909609, 0.16727162, 0.10337669,
       0.10459583, 0.08151746, 0.08099145, 0.13244984, 0.09009501,
       0.08577049, 0.1593141 , 0.10189177, 0.06271735, 0.08466493,
       0.10121841, 0.07868844, 0.08911118, 0.03912072, 0.14262589,
       0.        , 0.15121332, 0.06574573, 0.12410991, 0.13837229,
       0.11224345, 0.01789827, 0.11161535, 0.23463804, 0.        ,
       0.23511284, 0.10505007, 0.08272087, 0.09881305, 0.11947016,
       0.18879842, 0.06200539, 0.12882753, 0.03454895, 0.0732164 ,
       0.04349572, 0.03477916, 0.14061109, 0.05580235, 0.06931995,
       0.17437996, 0.06273588, 0.18685945, 0.13173708, 0.19697168,
       0.0860222 , 0.04784851, 0.05309822, 0.11713723, 0.11618649,
       0.08020742, 0.13173575, 0.12567805, 0.11011316, 0.11253827,
       0.06927818, 0.05249673, 0.06998077, 0.17630068, 0.019691  ,
       0.06299471, 0.        , 0.04131136, 0.16834334, 0.16636984,
       0.16007626, 0.13066622, 0.05953628, 0.06396094, 0.0835143 ,
       0.11061305, 0.05754624, 0.12489843, 0.04055475, 0.11036352,
       0.23637441, 0.1723661 , 0.15959235, 0.12768782, 0.03970117,
       0.12656499, 0.10153848, 0.087535  , 0.07801273, 0.04887971,
       0.07601121, 0.15863594, 0.12997598, 0.17174664, 0.1588518 ,
       0.16352905, 0.        , 0.20133968, 0.06177318, 0.21227003,
       0.05325322, 0.2458838 , 0.0791981 , 0.2104408 , 0.0256104 ,
       0.05490908, 0.        , 0.06644867, 0.19227221, 0.054237  ,
       0.17603014, 0.1415468 , 0.14237978, 0.13999595, 0.0908282 ,
       0.02743039, 0.12609024, 0.12751453, 0.08730131, 0.06429074,
       0.02272203, 0.07660775, 0.0841973 , 0.16069113, 0.02097173,
       0.10712807, 0.11368162, 0.08180118, 0.04602267, 0.15283448,
       0.11061201, 0.09866194, 0.06665448, 0.1020368 , 0.02403841,
       0.05401678, 0.02712118, 0.07628983, 0.08038818, 0.11797576,
       0.15777574, 0.1145533 , 0.        , 0.15780697, 0.13768403,
       0.11894907, 0.12464479, 0.2598933 , 0.13197444, 0.0596429 ,
       0.18953605, 0.05415311, 0.14455504, 0.        , 0.05945133,
       0.2088687 , 0.16636295, 0.02755368, 0.14660436, 0.02588857,
       0.0340486 , 0.13092248, 0.10858333, 0.143653  , 0.13469003,
       0.17132232, 0.08928005, 0.09393675, 0.09416318, 0.0425134 ,
       0.20677438, 0.0311612 , 0.14498578, 0.07473646, 0.04547424,
       0.13875263, 0.04493846, 0.11854619, 0.        , 0.08213275,
       0.12420622, 0.05279809, 0.        , 0.10765274, 0.23832918,
       0.10155095, 0.06126034, 0.01977483, 0.11680023, 0.14743377,
       0.05388142, 0.10753794, 0.09170279, 0.12466796, 0.13965493,
       0.1063607 , 0.17320896, 0.02628817, 0.22382922, 0.16630539,
       0.09771064, 0.05300349, 0.05709289, 0.06568749, 0.05005085,
       0.14531072, 0.1755074 , 0.12444585, 0.27154972, 0.07373926,
       0.09235413, 0.04472537, 0.0640034 , 0.        , 0.06287319,
       0.06729943, 0.16240974, 0.14108306, 0.13519788, 0.09344431,
       0.07128826, 0.02642704, 0.        , 0.07309867, 0.14682918,
       0.03862007, 0.13632805, 0.05764826, 0.09348958, 0.12159664,
       0.0442534 , 0.09906253, 0.        , 0.10386353, 0.11311894,
       0.09489116, 0.09767993, 0.19649142, 0.10259957, 0.04214032,
       0.11227209, 0.10451059, 0.04570411, 0.10211763, 0.06576243,
       0.0494782 , 0.15377185, 0.12086846, 0.13345557, 0.09527623,
       0.07419947, 0.05184791, 0.06542655, 0.04931013, 0.14717614,
       0.14126028, 0.04925315, 0.1204962 , 0.21727631, 0.10344644,
       0.08267066, 0.10632262, 0.13960948, 0.0377441 , 0.11664498,
       0.07821427, 0.25367009, 0.10212021, 0.10001117, 0.08903592,
       0.23132741, 0.04823949, 0.07175556, 0.04722405, 0.13786349,
       0.04011116, 0.0489358 , 0.12580649, 0.05784622, 0.11353166,
       0.03277089, 0.15190914, 0.03328972, 0.03097662, 0.06207895,
       0.0950657 , 0.09096111, 0.27803571, 0.15389615, 0.04020995,
       0.1727239 , 0.09757951, 0.10126777, 0.17436353, 0.1305113 ,
       0.04969486, 0.        , 0.10953318, 0.20455832, 0.12035901,
       0.11629737, 0.17992339, 0.04192502, 0.05263725, 0.05372548,
       0.23063474, 0.09124495, 0.08695596, 0.03033284, 0.07067235,
       0.03749226, 0.06123145, 0.28273974, 0.08833659, 0.06836809,
       0.09019429, 0.07003178, 0.08640897, 0.07513026, 0.08039066,
       0.07555192, 0.13096218, 0.08022346, 0.0796214 , 0.06975442,
       0.03622779, 0.05654447, 0.10109405, 0.03833604, 0.15808703,
       0.08128375, 0.08615018, 0.19517779, 0.08893428, 0.07796771,
       0.03443381, 0.10691045, 0.05098688, 0.04328519, 0.10144956,
       0.08412429, 0.05923732, 0.07027514, 0.19600673, 0.04812051,
       0.14123947, 0.05643584, 0.05312604, 0.05594183, 0.19402443,
       0.09210422, 0.05144376, 0.17012179, 0.11144097, 0.        ,
       0.08058097, 0.        , 0.12336465, 0.06089634, 0.13228396,
       0.01719942, 0.10537408, 0.14079955, 0.09397306, 0.10564332,
       0.0809875 , 0.05983938, 0.16223905, 0.15464884, 0.        ,
       0.04965039, 0.04710806, 0.11743094, 0.03850458, 0.        ,
       0.10361138, 0.        , 0.16393129, 0.0378243 , 0.09461635,
       0.08247602, 0.14344103, 0.        , 0.08105165, 0.06823541,
       0.10363363, 0.05923584, 0.08536802, 0.15715862, 0.04298854,
       0.        , 0.12348747, 0.1036733 , 0.08675048, 0.06256055,
       0.06617038, 0.023153  , 0.        , 0.        , 0.03987585,
       0.09328575, 0.11504961, 0.07770557, 0.07032594, 0.02667601,
       0.088408  , 0.13817124, 0.13916191, 0.03087357, 0.12383746,
       0.23059587, 0.26796288, 0.04317257, 0.12459795, 0.09196801,
       0.22440414, 0.03717709, 0.11017174, 0.08453832, 0.14991184,
       0.22208911, 0.10899709, 0.10813879, 0.13115938, 0.07123873,
       0.07548893, 0.10205291, 0.07998114, 0.12914556, 0.11877618,
       0.        , 0.25680319, 0.07477471, 0.12486312, 0.13981513,
       0.11405499, 0.09749679, 0.14868259, 0.13286288, 0.07127635,
       0.10699142, 0.10225386, 0.14315055, 0.0360085 , 0.02616267,
       0.045982  , 0.07369153, 0.05269289, 0.14051728, 0.06082863,
       0.09022351, 0.04757257, 0.00925881, 0.10959798, 0.04459178,
       0.07523306, 0.07620518, 0.15328288, 0.10768308, 0.0359473 ,
       0.03364971, 0.04201232, 0.10097695, 0.06151382, 0.12056755,
       0.08948083, 0.0803316 , 0.0990596 , 0.10475909, 0.10901812,
       0.07959552, 0.17066328, 0.04290026, 0.08316988, 0.09655001,
       0.13363793, 0.        , 0.01302815, 0.04193022, 0.07270829,
       0.145127  , 0.09173976, 0.06455346, 0.01704101, 0.10685709,
       0.03591333, 0.17219688, 0.15660571, 0.0786619 , 0.05114561,
       0.        , 0.09955718, 0.10160075, 0.16407538, 0.02960352,
       0.09813175, 0.        , 0.05172693, 0.10419871, 0.04497884,
       0.14897946, 0.11647043, 0.11374945, 0.1338449 , 0.05566729,
       0.04545451, 0.0973627 , 0.14846876, 0.06885662, 0.0381273 ,
       0.08295152, 0.09855171, 0.08961842, 0.06903189, 0.1311048 ,
       0.07887665, 0.20416822, 0.11646294, 0.10481228, 0.00387706,
       0.07438945, 0.15863695, 0.        , 0.23419137, 0.17706347,
       0.26252319, 0.09299458, 0.10772726, 0.1252514 , 0.05734607,
       0.08857531, 0.05628039, 0.11840483, 0.1826285 , 0.08880825,
       0.09084601, 0.01700102, 0.18123582, 0.06260989, 0.0551184 ,
       0.11922278, 0.10217589, 0.07860764, 0.04548456, 0.04657339,
       0.06297447, 0.09811293, 0.17817421, 0.11390134, 0.03841247,
       0.10460498, 0.21074551, 0.07563356, 0.03532216, 0.04906116,
       0.10308436, 0.09282327, 0.08562362, 0.14322812, 0.1729419 ,
       0.1443142 , 0.10690951, 0.10899005, 0.1016263 , 0.2383534 ,
       0.10288863, 0.14746625, 0.14283957, 0.09313653, 0.20204842,
       0.11011259, 0.27768096, 0.06317453, 0.07944607, 0.        ,
       0.03895899, 0.18846855, 0.15633207, 0.13548295, 0.03662368,
       0.05658947, 0.19147757, 0.14584706, 0.10316047, 0.0373302 ,
       0.12133939, 0.        , 0.15289417, 0.14152588, 0.02320639,
       0.05684525, 0.21037668, 0.06286739, 0.12345047, 0.08886457,
       0.09751591, 0.03232132, 0.07578412, 0.09254484, 0.07704462,
       0.08335279, 0.06627843, 0.07728573, 0.15254973, 0.08405529,
       0.06363305, 0.05235293, 0.19309722, 0.07446129, 0.16773875,
       0.14263397])

In [33]:
recommend('1984')

[['Animal Farm',
  'George Orwell',
  'http://images.amazon.com/images/P/0451526341.01.MZZZZZZZ.jpg'],
 ["The Handmaid's Tale",
  'Margaret Atwood',
  'http://images.amazon.com/images/P/0449212602.01.MZZZZZZZ.jpg'],
 ['Brave New World',
  'Aldous Huxley',
  'http://images.amazon.com/images/P/0060809833.01.MZZZZZZZ.jpg'],
 ['The Vampire Lestat (Vampire Chronicles, Book II)',
  'ANNE RICE',
  'http://images.amazon.com/images/P/0345313860.01.MZZZZZZZ.jpg'],
 ['The Hours : A Novel',
  'Michael Cunningham',
  'http://images.amazon.com/images/P/0312243022.01.MZZZZZZZ.jpg'],
 ['Fahrenheit 451',
  'Ray Bradbury',
  'http://images.amazon.com/images/P/3257208626.01.MZZZZZZZ.jpg'],
 ['The Catcher in the Rye',
  'J.D. Salinger',
  'http://images.amazon.com/images/P/0316769487.01.MZZZZZZZ.jpg']]

In [34]:
import pickle
pickle.dump(pt,open('pt.pkl','wb'))
pickle.dump(books,open('books.pkl','wb'))
pickle.dump(similarity_score,open('similarity_score.pkl','wb'))

In [28]:
import pickle
pickle.dump(popular_df,open('popular.pkl','wb'))